spring:
  application:
    name: currency-conversion-service

server:
  port: 8100

service.url.exchange: http://localhost:8000/

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#ribbon.eureka.enable: false # it is not necessary because now it use eureka
#currency-exchange-service.ribbon.listOfServers: localhost:8000, localhost:8001 # it is not necessary because now it use eureka

